---
services:
  n8n:
    stdin_open: true
    tty: true
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    image: ghcr.io/n8n-io/n8n:1.101.1
    environment:
      - WEBHOOK_URL=https://n8n.local.ruler23.com

volumes:
  n8n_data:
    external: true
    name: n8n_data