---
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd@sha256:c2f1826a3d231b9506554a60447e763157fd8ba4f600a4a864d6d0ddae00a0aa
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /data/usenet:/data/usenet:rw
    ports:
      - 8080:8080
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000 # Matches your 'ruler' user ID
      - PGID=1000 # Matches your 'ruler' group ID
      - TZ=America/New_York
      - USER=ruler # Optional: WebUI login
      - PASS=kalista23 # Optional: WebUI password
      - WHITELIST=127.0.0.1,10.0.0.*,172.16.0.0/12 # Allow local network access
      - HOST_WHITELIST=transmission,10.0.0.37,10.0.0.* # Tells Transmission it's okay to be called 'transmission'
    volumes:
      - /home/ruler/appdata/transmission:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/watch:/watch # Optional: auto-start torrents
    ports:
      - 9091:9091 # Web UI
      - 51413:51413 # Torrent traffic (TCP)
      - 51413:51413/udp # Torrent traffic (UDP)
    restart: unless-stopped
    
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
    container_name: flaresolverr
    ports:
      - '8191:8191'
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
