---
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd@sha256:87c97fa81966adb5cf511ae62b6681a37136c32f1ad7190b0b8b4d12d766ea9f
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /data/usenet:/data/usenet:rw
    ports:
      - 8080:8080
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000 # Matches your 'ruler' user ID
      - PGID=1000 # Matches your 'ruler' group ID
      - TZ=America/New_York
      - USER=ruler # Optional: WebUI login
      - PASS=kalista23 # Optional: WebUI password
      - WHITELIST=127.0.0.1,192.168.1.* # Allow local network access
    volumes:
      - /path/to/appdata/transmission:/config
      - /path/to/downloads:/downloads
      - /path/to/watch/folder:/watch # Optional: auto-start torrents
    ports:
      - 9091:9091 # Web UI
      - 51413:51413 # Torrent traffic (TCP)
      - 51413:51413/udp # Torrent traffic (UDP)
    restart: unless-stopped
    
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
    container_name: flaresolverr
    ports:
      - '8191:8191'
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
