---
services:
  adguardhome:
    image: adguard/adguardhome@sha256:7157eb1dc3b26c7af1d6898759a7b3f7d0fa09891fbd2d3caa6abc1057a9179b
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /home/ruler/AdGuardHome/workdir:/opt/adguardhome/work
      - /home/ruler/AdGuardHome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
