services:
  twingate-connector:
    image: twingate/connector@sha256:f5aded82f662144c56c87e4238ea4a20abcc525edc5ad7cdecdac187cf274520
    environment:
      - TWINGATE_NETWORK=$TWINGATE_NETWORK
      - TWINGATE_ACCESS_TOKEN=$TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN=$TWINGATE_REFRESH_TOKEN
      - TWINGATE_LABEL_HOSTNAME=${HOSTNAME}
      - TWINGATE_LABEL_DEPLOYED_BY=docker
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647