services:
  twingate-connector:
    image: twingate/connector@sha256:833e7a968f1b3a5ad79b88b04f82aad1bfc8621f61b6b35f01be2411d35beba9
    environment:
      - TWINGATE_NETWORK=$TWINGATE_NETWORK
      - TWINGATE_ACCESS_TOKEN=$TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN=$TWINGATE_REFRESH_TOKEN
      - TWINGATE_LABEL_HOSTNAME=${HOSTNAME}
      - TWINGATE_LABEL_DEPLOYED_BY=docker
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647