---
services:
    cloudflared:
        image: cloudflare/cloudflared@sha256:4f6655284ab3d252b7f28fedb19fe6c8fc82ee5b1295c20ac74d475e5398a52d
        restart: unless-stopped
        command: tunnel --no-autoupdate run --token $CF_TOKEN