---
services:
    cloudflared:
        image: cloudflare/cloudflared@sha256:072c067d25ccbe61d46e18f0d0723255f2bb5304f7317caa95b27031520ff92c
        restart: unless-stopped
        command: tunnel --no-autoupdate run --token $CF_TOKEN