---
services:
    cloudflared:
        image: cloudflare/cloudflared@sha256:ff69a2225ad7c6f85ed84fbd5f3087df46202426b2388ec60214098e0adf05e9
        restart: unless-stopped
        command: tunnel --no-autoupdate run --token $CF_TOKEN