---
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin@sha256:1574f396ec9a235c980a6e2e2e1a297eaef4d561b4eade522eb1143e79441332
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ruler/jellyfin/config:/config
      - /home/ruler/jellyfin/cache:/cache
    restart: unless-stopped
