---
services:
  portainer:
    image: portainer/portainer-ce@sha256:09db0c204595cab39981fd559faa0a2f4e0f67387eb0b14b2926adf4e058a6d1
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data:
    external: true