---
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:2.3.0
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=America/New_York
       ports:
            - 5055:5055
       volumes:
            - /home/ruler/jellyseerr/config:/app/config
       restart: unless-stopped
